antiAffinity: "soft"

resources:
  requests:
    cpu: "300m"
    memory: "1024M"
  limits:
    cpu: "1500m"
    memory: "1024M"

volumeClaimTemplate:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: "10G"
