kind: DaemonSet

image:
  repository: cr.fluentbit.io/fluent/fluent-bit
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

extraVolumes:
  - name: wildfly-logs
    persistentVolumeClaim:
      claimName: wildfly-data

extraVolumeMounts:
  - name: wildfly-logs
    mountPath: /mnt/wildfly-logs
    readOnly: true

config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

  inputs: |
    [INPUT]
        Name tail
        Path /mnt/wildfly-logs/log/server.log
        Tag wildfly.server.log
        Multiline On
        Parser_Firstline wildfly_server
        Refresh_Interval 10
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Path /mnt/wildfly-logs/log/gc.log
        Tag wildfly.gc.log
        Multiline On
        Parser_Firstline wildfly_gc
        Refresh_Interval 10
        Skip_Long_Lines On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  outputs: |
    [OUTPUT]
        Name es
        Match wildfly.server.log
        Host elasticsearch-master.wildfly.svc.cluster.local
        Port 9200
        HTTP_User elastic
        HTTP_Passwd ELASTIC_PASSWORD
        TLS On
        TLS.Verify Off
        Logstash_Format On
        Replace_Dots On
        Retry_Limit False
        Suppress_Type_Name On
        Logstash_Prefix wildfly-server-log

    [OUTPUT]
        Name es
        Match wildfly.gc.log
        Host elasticsearch-master.wildfly.svc.cluster.local
        Port 9200
        HTTP_User elastic
        HTTP_Passwd ELASTIC_PASSWORD
        TLS On
        TLS.Verify Off
        Logstash_Format On
        Replace_Dots On
        Retry_Limit False
        Suppress_Type_Name On
        Logstash_Prefix wildfly-gc-log

    [OUTPUT]
        Name es
        Match kube.var.log.containers.*
        Host elasticsearch-master.wildfly.svc.cluster.local
        Port 9200
        HTTP_User elastic
        HTTP_Passwd ELASTIC_PASSWORD
        TLS On
        TLS.Verify Off
        Logstash_Format On
        Replace_Dots On
        Retry_Limit False
        Suppress_Type_Name On
        Logstash_Prefix kubernetes-logs

  customParsers: |
    [PARSER]
        Name wildfly_server
        Format regex
        Regex ^\d{4}-\d{2}-\d{2}
        Time_Keep On

    [PARSER]
        Name wildfly_gc
        Format regex
        Regex ^\[
        Time_Keep On
