apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wildfly
  namespace: wildfly
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wildfly
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
